name: Build and Release

on:
  push: 
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Setup gradle
        uses: gradle/gradle-build-action@v3
      - name: Gradle powers
        run: chmod +xrw ./gradlew
      - name: Build Release
        run: ./gradlew assembleRelease --no-daemon
      - name: Release the release to release section
        uses: actions/upload-artifact@v4
        with:
          name: Shape
          path: app/build/outputs/apk/release/app-release.apk
      
